### ISSUE TITLE
Java class missing

### ISSUE THREAD

**Issue by lvamsavarthan** [dimanych/GuardianNews#1]
DaggerAppComponent.class is missing , please upload it

**Comment by dimanych** [comment]
No need, DaggerAppComponent generate by automatically

**Comment by lvamsavarthan** [comment]
how to generate it? , can you explain me , i am a beginner

**Comment by dimanych** [comment]
For understanding, you should learn dependency injection using Dagger

**Comment by lvamsavarthan** [comment]
will it be generated in android studio 2.3.3?

**Comment by dimanych** [comment]
Use Android Studio 3+
